// <auto-generated />
using System;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

using Stambat.Infrastructure.Persistence;

#nullable disable

namespace Stambat.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Stambat.Domain.Entities.CardTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EarnedStampUrl")
                        .HasColumnType("text");

                    b.Property<string>("EmptyStampUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrlOverride")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryColorOverride")
                        .HasColumnType("text");

                    b.Property<string>("RewardDescription")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryColorOverride")
                        .HasColumnType("text");

                    b.Property<int>("StampsRequired")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TermsAndConditions")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("CardTemplate");
                });

            modelBuilder.Entity("Stambat.Domain.Entities.Identity.Authentication.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019cd45e-7cf2-7f36-9595-2bd07dc9e25b"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            IsDeleted = false,
                            Name = "Tenants.View"
                        },
                        new
                        {
                            Id = new Guid("019cd45e-7cfc-7f11-9cdc-4581e5854eac"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            IsDeleted = false,
                            Name = "Tenants.Add"
                        },
                        new
                        {
                            Id = new Guid("019cd45e-7cfc-7839-a733-b7b1c30138d4"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            IsDeleted = false,
                            Name = "Tenants.Edit"
                        },
                        new
                        {
                            Id = new Guid("019cd45e-7cfc-7807-8f5e-f4cce0b1ee3a"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            IsDeleted = false,
                            Name = "Tenants.Delete"
                        },
                        new
                        {
                            Id = new Guid("019cd47e-8346-7a3e-9c1c-f0d3a65d4091"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            IsDeleted = false,
                            Name = "Tenants.Setup"
                        },
                        new
                        {
                            Id = new Guid("019cd45e-7cfc-7947-88e3-7c06f899920f"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            IsDeleted = false,
                            Name = "Users.View"
                        },
                        new
                        {
                            Id = new Guid("019cd45e-7cfc-78d6-8548-e20dbdadc04b"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            IsDeleted = false,
                            Name = "Users.Add"
                        },
                        new
                        {
                            Id = new Guid("019cd45e-7cfc-76d3-b56e-cc03d8854ff4"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            IsDeleted = false,
                            Name = "Users.Edit"
                        },
                        new
                        {
                            Id = new Guid("019cd45e-7cfc-70e9-895b-4175ca7f5ee6"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            IsDeleted = false,
                            Name = "Users.Delete"
                        },
                        new
                        {
                            Id = new Guid("019cd45e-7cfc-717e-b9df-56b9565cc5e1"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            IsDeleted = false,
                            Name = "Invitations.View"
                        },
                        new
                        {
                            Id = new Guid("019cd45e-7cfc-7ef1-9e1a-8ae8e3ff78f6"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            IsDeleted = false,
                            Name = "Invitations.Add"
                        },
                        new
                        {
                            Id = new Guid("019cd45e-7cfc-717f-853f-ed4d8c572e50"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            IsDeleted = false,
                            Name = "Invitations.Edit"
                        },
                        new
                        {
                            Id = new Guid("019cd45e-7cfc-7156-83d3-81d9e8951b34"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            IsDeleted = false,
                            Name = "Invitations.Delete"
                        },
                        new
                        {
                            Id = new Guid("019cd45e-7cfc-71fd-b726-7446578cf8b8"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            IsDeleted = false,
                            Name = "Cards.View"
                        },
                        new
                        {
                            Id = new Guid("019cd45e-7cfc-75ec-9acf-136b67adda34"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            IsDeleted = false,
                            Name = "Cards.Add"
                        },
                        new
                        {
                            Id = new Guid("019cd45e-7cfc-7499-a257-849fd24c2871"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            IsDeleted = false,
                            Name = "Cards.Edit"
                        },
                        new
                        {
                            Id = new Guid("019cd45e-7cfc-79ad-8fd5-cf99cd27ad06"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            IsDeleted = false,
                            Name = "Cards.Delete"
                        },
                        new
                        {
                            Id = new Guid("019cd45e-7cfc-7144-85d7-a624389a5bda"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            IsDeleted = false,
                            Name = "Rewards.View"
                        },
                        new
                        {
                            Id = new Guid("019cd45e-7cfc-7af3-8e82-501087bdc3fd"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            IsDeleted = false,
                            Name = "Rewards.Add"
                        },
                        new
                        {
                            Id = new Guid("019cd45e-7cfc-739a-9ceb-77a6fae361a7"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            IsDeleted = false,
                            Name = "Rewards.Edit"
                        },
                        new
                        {
                            Id = new Guid("019cd45e-7cfc-72ca-892a-4c5484b063af"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            IsDeleted = false,
                            Name = "Rewards.Delete"
                        },
                        new
                        {
                            Id = new Guid("019cd45e-7cfc-78ba-b9fc-d69399cdc202"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            IsDeleted = false,
                            Name = "Scan.Stamping"
                        },
                        new
                        {
                            Id = new Guid("019cd45e-7cfc-735f-ac03-e6b5ebe67f6e"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            IsDeleted = false,
                            Name = "Scan.Redeem"
                        },
                        new
                        {
                            Id = new Guid("019cd465-18f5-7e38-951f-99444e306980"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            IsDeleted = false,
                            Name = "System.Manage"
                        },
                        new
                        {
                            Id = new Guid("019cd465-18ff-7956-a606-0c8f350e2330"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            IsDeleted = false,
                            Name = "System.Logs.View"
                        },
                        new
                        {
                            Id = new Guid("019cd465-18ff-7481-be6f-34e04e75f169"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            IsDeleted = false,
                            Name = "System.Audit.View"
                        },
                        new
                        {
                            Id = new Guid("019cd465-18ff-77ba-b57f-2026a084e84a"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            IsDeleted = false,
                            Name = "System.Settings.Edit"
                        },
                        new
                        {
                            Id = new Guid("019cd465-18ff-733b-9eed-eaadb6650b4c"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            IsDeleted = false,
                            Name = "Tenants.Manage"
                        });
                });

            modelBuilder.Entity("Stambat.Domain.Entities.Identity.Authentication.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReasonRevoked")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStampAtIssue")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("TokenFamilyId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("ReplacedByTokenId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "TokenFamilyId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Stambat.Domain.Entities.Identity.Authentication.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019cd46a-80a8-76a2-b7eb-20ca5903c25e"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            Description = "Full system administration and management.",
                            IsDeleted = false,
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            Id = new Guid("019cd46a-80b3-7eb0-9861-254e15e297db"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            Description = "Administration of a specific tenant and its resources.",
                            IsDeleted = false,
                            Name = "TenantAdmin"
                        },
                        new
                        {
                            Id = new Guid("019cd46a-80b3-712e-8b82-edbae70f6a0d"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            Description = "Staff access for scanning and stamping loyalty cards.",
                            IsDeleted = false,
                            Name = "Merchant"
                        },
                        new
                        {
                            Id = new Guid("019cd46a-80b3-7a1a-a1b1-254e15e297db"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            Description = "Middle management for specific tenant features and staff management.",
                            IsDeleted = false,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = new Guid("019cd46a-80b3-7d68-8834-46e510948741"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            Description = "End-user access for viewing cards and rewards.",
                            IsDeleted = false,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Stambat.Domain.Entities.Identity.Authentication.RolePermission", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("PermissionId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cf2-7f36-9595-2bd07dc9e25b"),
                            RoleId = new Guid("019cd46a-80a8-76a2-b7eb-20ca5903c25e")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-7f11-9cdc-4581e5854eac"),
                            RoleId = new Guid("019cd46a-80a8-76a2-b7eb-20ca5903c25e")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-7839-a733-b7b1c30138d4"),
                            RoleId = new Guid("019cd46a-80a8-76a2-b7eb-20ca5903c25e")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-7807-8f5e-f4cce0b1ee3a"),
                            RoleId = new Guid("019cd46a-80a8-76a2-b7eb-20ca5903c25e")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd47e-8346-7a3e-9c1c-f0d3a65d4091"),
                            RoleId = new Guid("019cd46a-80a8-76a2-b7eb-20ca5903c25e")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-7947-88e3-7c06f899920f"),
                            RoleId = new Guid("019cd46a-80a8-76a2-b7eb-20ca5903c25e")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-78d6-8548-e20dbdadc04b"),
                            RoleId = new Guid("019cd46a-80a8-76a2-b7eb-20ca5903c25e")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-76d3-b56e-cc03d8854ff4"),
                            RoleId = new Guid("019cd46a-80a8-76a2-b7eb-20ca5903c25e")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-70e9-895b-4175ca7f5ee6"),
                            RoleId = new Guid("019cd46a-80a8-76a2-b7eb-20ca5903c25e")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-717e-b9df-56b9565cc5e1"),
                            RoleId = new Guid("019cd46a-80a8-76a2-b7eb-20ca5903c25e")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-7ef1-9e1a-8ae8e3ff78f6"),
                            RoleId = new Guid("019cd46a-80a8-76a2-b7eb-20ca5903c25e")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-717f-853f-ed4d8c572e50"),
                            RoleId = new Guid("019cd46a-80a8-76a2-b7eb-20ca5903c25e")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-7156-83d3-81d9e8951b34"),
                            RoleId = new Guid("019cd46a-80a8-76a2-b7eb-20ca5903c25e")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-71fd-b726-7446578cf8b8"),
                            RoleId = new Guid("019cd46a-80a8-76a2-b7eb-20ca5903c25e")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-75ec-9acf-136b67adda34"),
                            RoleId = new Guid("019cd46a-80a8-76a2-b7eb-20ca5903c25e")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-7499-a257-849fd24c2871"),
                            RoleId = new Guid("019cd46a-80a8-76a2-b7eb-20ca5903c25e")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-79ad-8fd5-cf99cd27ad06"),
                            RoleId = new Guid("019cd46a-80a8-76a2-b7eb-20ca5903c25e")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-7144-85d7-a624389a5bda"),
                            RoleId = new Guid("019cd46a-80a8-76a2-b7eb-20ca5903c25e")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-7af3-8e82-501087bdc3fd"),
                            RoleId = new Guid("019cd46a-80a8-76a2-b7eb-20ca5903c25e")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-739a-9ceb-77a6fae361a7"),
                            RoleId = new Guid("019cd46a-80a8-76a2-b7eb-20ca5903c25e")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-72ca-892a-4c5484b063af"),
                            RoleId = new Guid("019cd46a-80a8-76a2-b7eb-20ca5903c25e")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-78ba-b9fc-d69399cdc202"),
                            RoleId = new Guid("019cd46a-80a8-76a2-b7eb-20ca5903c25e")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-735f-ac03-e6b5ebe67f6e"),
                            RoleId = new Guid("019cd46a-80a8-76a2-b7eb-20ca5903c25e")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd465-18f5-7e38-951f-99444e306980"),
                            RoleId = new Guid("019cd46a-80a8-76a2-b7eb-20ca5903c25e")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd465-18ff-7956-a606-0c8f350e2330"),
                            RoleId = new Guid("019cd46a-80a8-76a2-b7eb-20ca5903c25e")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd465-18ff-7481-be6f-34e04e75f169"),
                            RoleId = new Guid("019cd46a-80a8-76a2-b7eb-20ca5903c25e")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd465-18ff-77ba-b57f-2026a084e84a"),
                            RoleId = new Guid("019cd46a-80a8-76a2-b7eb-20ca5903c25e")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd465-18ff-733b-9eed-eaadb6650b4c"),
                            RoleId = new Guid("019cd46a-80a8-76a2-b7eb-20ca5903c25e")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cf2-7f36-9595-2bd07dc9e25b"),
                            RoleId = new Guid("019cd46a-80b3-7eb0-9861-254e15e297db")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-7839-a733-b7b1c30138d4"),
                            RoleId = new Guid("019cd46a-80b3-7eb0-9861-254e15e297db")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-7947-88e3-7c06f899920f"),
                            RoleId = new Guid("019cd46a-80b3-7eb0-9861-254e15e297db")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-78d6-8548-e20dbdadc04b"),
                            RoleId = new Guid("019cd46a-80b3-7eb0-9861-254e15e297db")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-76d3-b56e-cc03d8854ff4"),
                            RoleId = new Guid("019cd46a-80b3-7eb0-9861-254e15e297db")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-70e9-895b-4175ca7f5ee6"),
                            RoleId = new Guid("019cd46a-80b3-7eb0-9861-254e15e297db")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-717e-b9df-56b9565cc5e1"),
                            RoleId = new Guid("019cd46a-80b3-7eb0-9861-254e15e297db")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-7ef1-9e1a-8ae8e3ff78f6"),
                            RoleId = new Guid("019cd46a-80b3-7eb0-9861-254e15e297db")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-717f-853f-ed4d8c572e50"),
                            RoleId = new Guid("019cd46a-80b3-7eb0-9861-254e15e297db")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-7156-83d3-81d9e8951b34"),
                            RoleId = new Guid("019cd46a-80b3-7eb0-9861-254e15e297db")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-71fd-b726-7446578cf8b8"),
                            RoleId = new Guid("019cd46a-80b3-7eb0-9861-254e15e297db")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-75ec-9acf-136b67adda34"),
                            RoleId = new Guid("019cd46a-80b3-7eb0-9861-254e15e297db")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-7499-a257-849fd24c2871"),
                            RoleId = new Guid("019cd46a-80b3-7eb0-9861-254e15e297db")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-79ad-8fd5-cf99cd27ad06"),
                            RoleId = new Guid("019cd46a-80b3-7eb0-9861-254e15e297db")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-7144-85d7-a624389a5bda"),
                            RoleId = new Guid("019cd46a-80b3-7eb0-9861-254e15e297db")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-7af3-8e82-501087bdc3fd"),
                            RoleId = new Guid("019cd46a-80b3-7eb0-9861-254e15e297db")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-739a-9ceb-77a6fae361a7"),
                            RoleId = new Guid("019cd46a-80b3-7eb0-9861-254e15e297db")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-72ca-892a-4c5484b063af"),
                            RoleId = new Guid("019cd46a-80b3-7eb0-9861-254e15e297db")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-78ba-b9fc-d69399cdc202"),
                            RoleId = new Guid("019cd46a-80b3-7eb0-9861-254e15e297db")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-735f-ac03-e6b5ebe67f6e"),
                            RoleId = new Guid("019cd46a-80b3-7eb0-9861-254e15e297db")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cf2-7f36-9595-2bd07dc9e25b"),
                            RoleId = new Guid("019cd46a-80b3-712e-8b82-edbae70f6a0d")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-7947-88e3-7c06f899920f"),
                            RoleId = new Guid("019cd46a-80b3-712e-8b82-edbae70f6a0d")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-71fd-b726-7446578cf8b8"),
                            RoleId = new Guid("019cd46a-80b3-712e-8b82-edbae70f6a0d")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-7144-85d7-a624389a5bda"),
                            RoleId = new Guid("019cd46a-80b3-712e-8b82-edbae70f6a0d")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-78ba-b9fc-d69399cdc202"),
                            RoleId = new Guid("019cd46a-80b3-712e-8b82-edbae70f6a0d")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-735f-ac03-e6b5ebe67f6e"),
                            RoleId = new Guid("019cd46a-80b3-712e-8b82-edbae70f6a0d")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cf2-7f36-9595-2bd07dc9e25b"),
                            RoleId = new Guid("019cd46a-80b3-7a1a-a1b1-254e15e297db")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-7947-88e3-7c06f899920f"),
                            RoleId = new Guid("019cd46a-80b3-7a1a-a1b1-254e15e297db")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-78d6-8548-e20dbdadc04b"),
                            RoleId = new Guid("019cd46a-80b3-7a1a-a1b1-254e15e297db")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-717e-b9df-56b9565cc5e1"),
                            RoleId = new Guid("019cd46a-80b3-7a1a-a1b1-254e15e297db")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-7ef1-9e1a-8ae8e3ff78f6"),
                            RoleId = new Guid("019cd46a-80b3-7a1a-a1b1-254e15e297db")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-71fd-b726-7446578cf8b8"),
                            RoleId = new Guid("019cd46a-80b3-7a1a-a1b1-254e15e297db")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-7144-85d7-a624389a5bda"),
                            RoleId = new Guid("019cd46a-80b3-7a1a-a1b1-254e15e297db")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-78ba-b9fc-d69399cdc202"),
                            RoleId = new Guid("019cd46a-80b3-7a1a-a1b1-254e15e297db")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-735f-ac03-e6b5ebe67f6e"),
                            RoleId = new Guid("019cd46a-80b3-7a1a-a1b1-254e15e297db")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-75ec-9acf-136b67adda34"),
                            RoleId = new Guid("019cd46a-80b3-7a1a-a1b1-254e15e297db")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cf2-7f36-9595-2bd07dc9e25b"),
                            RoleId = new Guid("019cd46a-80b3-7d68-8834-46e510948741")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd47e-8346-7a3e-9c1c-f0d3a65d4091"),
                            RoleId = new Guid("019cd46a-80b3-7d68-8834-46e510948741")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-71fd-b726-7446578cf8b8"),
                            RoleId = new Guid("019cd46a-80b3-7d68-8834-46e510948741")
                        },
                        new
                        {
                            PermissionId = new Guid("019cd45e-7cfc-7144-85d7-a624389a5bda"),
                            RoleId = new Guid("019cd46a-80b3-7d68-8834-46e510948741")
                        });
                });

            modelBuilder.Entity("Stambat.Domain.Entities.Identity.Authentication.UserRoleTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NULL");

                    b.HasIndex("UserId", "RoleId", "TenantId")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NOT NULL");

                    b.ToTable("UserRoleTenants");
                });

            modelBuilder.Entity("Stambat.Domain.Entities.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserCredentialsId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Stambat.Domain.Entities.Identity.UserCredentials", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserCredentials");
                });

            modelBuilder.Entity("Stambat.Domain.Entities.Identity.UserToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("Stambat.Domain.Entities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("Email", "TenantId", "RoleId")
                        .IsUnique()
                        .HasFilter("\"IsUsed\" = false");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("Stambat.Domain.Entities.StampTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("StampsAdded")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WalletPassId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId");

                    b.HasIndex("WalletPassId");

                    b.ToTable("StampTransaction");
                });

            modelBuilder.Entity("Stambat.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("JOD");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("TenantProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Asia/Amman");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Stambat.Domain.Entities.TenantProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasDefaultValue("#000000");

                    b.Property<string>("SecondaryColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasDefaultValue("#FFFFFF");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("TenantProfiles");
                });

            modelBuilder.Entity("Stambat.Domain.Entities.WalletPass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplePassSerialNumber")
                        .HasColumnType("text");

                    b.Property<Guid>("CardTemplateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentStamps")
                        .HasColumnType("integer");

                    b.Property<string>("GooglePayId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastStampedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CardTemplateId");

                    b.HasIndex("UserId");

                    b.ToTable("WalletPass");
                });

            modelBuilder.Entity("Stambat.Domain.Entities.CardTemplate", b =>
                {
                    b.HasOne("Stambat.Domain.Entities.Tenant", "Tenant")
                        .WithMany("CardTemplates")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Stambat.Domain.Entities.Identity.Authentication.RefreshToken", b =>
                {
                    b.HasOne("Stambat.Domain.Entities.Identity.Authentication.RefreshToken", "ReplacedByToken")
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Stambat.Domain.Entities.Identity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReplacedByToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Stambat.Domain.Entities.Identity.Authentication.RolePermission", b =>
                {
                    b.HasOne("Stambat.Domain.Entities.Identity.Authentication.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stambat.Domain.Entities.Identity.Authentication.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Stambat.Domain.Entities.Identity.Authentication.UserRoleTenant", b =>
                {
                    b.HasOne("Stambat.Domain.Entities.Identity.Authentication.Role", "Role")
                        .WithMany("UserRoleTenants")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stambat.Domain.Entities.Tenant", "Tenant")
                        .WithMany("UserRoleTenants")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stambat.Domain.Entities.Identity.User", "User")
                        .WithMany("UserRoleTenants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Stambat.Domain.Entities.Identity.User", b =>
                {
                    b.OwnsOne("Stambat.Domain.ValueObjects.FullName", "FullName", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("MiddleName")
                                .HasColumnType("text");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("FullName")
                        .IsRequired();
                });

            modelBuilder.Entity("Stambat.Domain.Entities.Identity.UserCredentials", b =>
                {
                    b.HasOne("Stambat.Domain.Entities.Identity.User", "User")
                        .WithOne("Credentials")
                        .HasForeignKey("Stambat.Domain.Entities.Identity.UserCredentials", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Stambat.Domain.Entities.Identity.UserToken", b =>
                {
                    b.HasOne("Stambat.Domain.Entities.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Stambat.Domain.Entities.Invitation", b =>
                {
                    b.HasOne("Stambat.Domain.Entities.Identity.Authentication.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stambat.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Role");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Stambat.Domain.Entities.StampTransaction", b =>
                {
                    b.HasOne("Stambat.Domain.Entities.Identity.User", "Merchant")
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stambat.Domain.Entities.WalletPass", "WalletPass")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletPassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");

                    b.Navigation("WalletPass");
                });

            modelBuilder.Entity("Stambat.Domain.Entities.TenantProfile", b =>
                {
                    b.HasOne("Stambat.Domain.Entities.Tenant", "Tenant")
                        .WithOne("TenantProfile")
                        .HasForeignKey("Stambat.Domain.Entities.TenantProfile", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Stambat.Domain.Entities.WalletPass", b =>
                {
                    b.HasOne("Stambat.Domain.Entities.CardTemplate", "CardTemplate")
                        .WithMany("IssuedPasses")
                        .HasForeignKey("CardTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stambat.Domain.Entities.Identity.User", "User")
                        .WithMany("WalletPasses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardTemplate");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Stambat.Domain.Entities.CardTemplate", b =>
                {
                    b.Navigation("IssuedPasses");
                });

            modelBuilder.Entity("Stambat.Domain.Entities.Identity.Authentication.Role", b =>
                {
                    b.Navigation("UserRoleTenants");
                });

            modelBuilder.Entity("Stambat.Domain.Entities.Identity.User", b =>
                {
                    b.Navigation("Credentials");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoleTenants");

                    b.Navigation("WalletPasses");
                });

            modelBuilder.Entity("Stambat.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("CardTemplates");

                    b.Navigation("TenantProfile");

                    b.Navigation("UserRoleTenants");
                });

            modelBuilder.Entity("Stambat.Domain.Entities.WalletPass", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
